inherit_gem:
  rubocop-config-umbrellio: lib/rubocop.rails.yml

AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - db/schema.rb
    - ciesta.gemspec

Metrics/LineLength:
  IgnoredPatterns: ['#.*']

Rails/SaveBang:
  Enabled: false
